name: Sanity

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-20.04
    container:
      image: srikanthds/modustoolbox-container

    steps:
    - uses: actions/checkout@v3

    - name: Sanity Test
      run: bash sanity_ci.sh
